#!/data/data/com.termux/files/user
clear

figlet -f slant "I LOVE YOU" |lolcat
sleep 2
echo " "
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
sleep 2 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
sleep 2 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
sleep 2 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
sleep 2 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
sleep 2 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
sleep 2
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
sleep 2 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
sleep 2 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
echo -e "\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m\e[36m I LOVE YOU \e[m " 
sleep 2

clear 
echo -e "\e[36m BY SEE NEXT TIME  \e[m " 
sleep 3
exit
